# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: fzpython2022
dependencies:
- python>3.6
- colorama
- cython
- h5py
- jupyter
- matplotlib
- numpy
- pip
- psutil
- scipy
- scikit-learn
- scikit-learn-intelex
- pandas

- pip:
  - terminaltables
  - tqdm
 # - mpi4py
 # - pycuda
