# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: fzpython2022
dependencies:

- git

- colorama
- cython

- h5py

- jupyter

- matplotlib

- numpy

- python>3.8
- pandas
- pip
- psutil
- pycuda

- scipy
- scikit-learn # conda install -c conda-forge scikit-learn
- scikit-learn-intelex


- pip:
  - terminaltables
  - tqdm
 # - mpi4py
 # - pycuda
